-- CRIAÇÃO DAS TABELAS

create table tb_aluno (
        id_aluno integer generated by default as identity,
        email varchar(200) not null,
        nome_aluno varchar(200) not null,
        senha varchar(200) not null,
        tb_curso_id_curso integer not null,
        primary key (id_aluno)
    )

    create table tb_categoria (
        id_categoria integer generated by default as identity,
        nome_categoria varchar(100) not null,
        primary key (id_categoria)
    )

    create table tb_curso (
        id_curso integer generated by default as identity,
        nome_curso varchar(50) not null,
        primary key (id_curso)
    )

    create table tb_imagem_item (
        id_imagem integer generated by default as identity,
        url_imagem,
        tb_item_id_item integer not null,
        primary key (id_imagem)
    )

    create table tb_item (
        id_item integer generated by default as identity,
        descricao varchar(500),
        nome_item varchar(200) not null,
        tb_aluno_id_aluno integer not null,
        tb_categoria_id_categoria integer not null,
        primary key (id_item)
    )

    create table tb_mensagem (
        id_mensagem integer generated by default as identity,
        data_envio timestamp(6) not null,
        mensagem text not null,
        tb_aluno_id_destinatario integer not null,
        tb_aluno_id_remetente integer not null,
        tb_troca_id_troca integer not null,
        primary key (id_mensagem)
    )

    create table tb_troca (
        id_troca integer generated by default as identity,
        data_criacao timestamp(6) not null,
        status varchar(10) not null check ((status in ('PENDENTE','ACEITA','RECUSADA'))),
        tb_item_id_item_desejado integer not null,
        tb_item_id_item_ofertado integer not null,
        tb_aluno_id_receptor integer not null,
        tb_aluno_id_solicitante integer not null,
        primary key (id_troca)
    )